# Generated by Django 2.2.6 on 2019-11-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_tracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
